format = """
$directory\
$git_branch\
$git_status\
$ruby\
$nodejs\
$dotnet\
$cmd_duration\
$character"""

[directory]
style = "cyan"
truncation_length = 1

[character]
success_symbol = "[✗](bold yellow)"
error_symbol = "[✗](bold red)"

[git_branch]
style = "purple"

[git_status]
style = "red"

[ruby]
style = "red"
format = "[$symbol($version)]($style) "

[nodejs]
style = "green"
format = "[$symbol($version)]($style) "

[dotnet]
style = "blue"
format = "[$symbol($version)]($style) "

[cmd_duration]
min_time = 2_000
style = "yellow"
